# Generated by Django 2.2 on 2019-05-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=20)),
                ('lyric', models.TextField()),
                ('accompaniment_url', models.TextField()),
                ('offset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('md5', models.CharField(max_length=32)),
                ('task_id', models.CharField(max_length=64)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_handle.Demo')),
            ],
        ),
    ]
