# Generated by Django 2.2 on 2019-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='target',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
