# Generated by Django 2.2 on 2019-04-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0002_audios_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('md5', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Audios',
        ),
        migrations.AddField(
            model_name='audio',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_handle.Demo'),
        ),
    ]
