# Generated by Django 2.2 on 2019-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0003_auto_20190425_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
