# Generated by Django 2.2 on 2019-05-05 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0005_auto_20190426_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='artist',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
