# Generated by Django 2.2 on 2019-05-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0006_demo_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='artist',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='demo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
