# Generated by Django 2.2 on 2019-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0007_auto_20190505_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='lyric',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
