# Generated by Django 2.2 on 2019-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0008_demo_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='accompaniment_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
