# Generated by Django 2.2 on 2019-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0009_demo_accompaniment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='offset',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
