# Generated by Django 2.2 on 2019-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0010_demo_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('PENDING', 'PENDING')], default='PENDING', max_length=10),
        ),
    ]
