# Generated by Django 2.2 on 2019-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_handle', '0011_audio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
